export { MovieDetail } from "./MovieDetail"
export { MovieList } from "./MovieList"
export { PageNotFound } from "./PageNotFound"
export { Search } from "./Search"
export { MovieGenres } from "./MovieGenres"
export { Genres } from "./Genres"
